/*
 *
 * User constants
 *
 */

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';

export const PATCH_USER_DATA_REQUEST = 'PATCH_USER_DATA_REQUEST';
export const PATCH_USER_DATA_SUCCESS = 'PATCH_USER_DATA_SUCCESS';
export const PATCH_USER_DATA_ERROR = 'PATCH_USER_DATA_ERROR';
