/*
 *
 * Testimonial constants
 *
 */

export const SUBMIT_TESTIMONIAL_REQUEST = 'SUBMIT_TESTIMONIAL_REQUEST';
export const SUBMIT_TESTIMONIAL_SUCCESS = 'SUBMIT_TESTIMONIAL_SUCCESS';
export const SUBMIT_TESTIMONIAL_ERROR = 'SUBMIT_TESTIMONIAL_ERROR';

export const FETCH_TESTIMONIAL_REQUEST = 'FETCH_TESTIMONIAL_REQUEST';
export const FETCH_TESTIMONIAL_SUCCESS = 'FETCH_TESTIMONIAL_SUCCESS';
export const FETCH_TESTIMONIAL_ERROR = 'FETCH_TESTIMONIAL_ERROR';
