/*
 *
 * Testimonial constants
 *
 */

export const SUBMIT_TESTIMONIAL_REQUEST = 'SUBMIT_TESTIMONIAL_REQUEST';
export const SUBMIT_TESTIMONIAL_SUCCESS = 'SUBMIT_TESTIMONIAL_SUCCESS';
export const SUBMIT_TESTIMONIAL_ERROR = 'SUBMIT_TESTIMONIAL_ERROR';

export const PATCH_TESTIMONIAL_REQUEST = 'PATCH_TESTIMONIAL_REQUEST';
export const PATCH_TESTIMONIAL_SUCCESS = 'PATCH_TESTIMONIAL_SUCCESS';
export const PATCH_TESTIMONIAL_ERROR = 'PATCH_TESTIMONIAL_ERROR';
