/*
 *
 * UserEdit constants
 *
 */

export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_ERROR = "POST_USER_DATA_ERROR"
