/*
 *
 * UserEdit constants
 *
 */

export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_ERROR = 'POST_USER_DATA_ERROR';

export const GET_USER_DATA_BY_ID_REQUEST = 'GET_DATA_BY_ID_REQUEST';
export const GET_USER_DATA_BY_ID_SUCCESS = 'GET_DATA_BY_ID_SUCCESS';
export const GET_USER_DATA_BY_ID_ERROR = 'GET_DATA_BY_ID_ERROR';
