/*
 *
 * BlogCategoryEditor constants
 *
 */

export const POST_BLOG_CATEGORY_REQUEST = 'POST_BLOG_CATEGORY_REQUEST';
export const POST_BLOG_CATEGORY_SUCCESS = 'POST_BLOG_CATEGORY_SUCCESS';
export const POST_BLOG_CATEGORY_ERROR = 'POST_BLOG_CATEGORY_ERROR';
