/*
 *
 * TestimonialEdit constants
 *
 */


export const SUBMIT_TESTIMONIAL_REQUEST = 'SUBMIT_TESTIMONIAL_REQUEST';
export const SUBMIT_TESTIMONIAL_SUCCESS = 'SUBMIT_TESTIMONIAL_SUCCESS';
export const SUBMIT_TESTIMONIAL_ERROR = 'SUBMIT_TESTIMONIAL_ERROR';

export const GET_DATA_BY_ID_REQUEST = 'GET_DATA_BY_ID_REQUEST';
export const GET_DATA_BY_ID_SUCCESS = 'GET_DATA_BY_ID_SUCCESS';
export const GET_DATA_BY_ID_ERROR = 'GET_DATA_BY_ID_ERROR';

export const PUT_DATA_BY_ID_REQUEST = 'PUT_DATA_BY_ID_REQUEST';
export const PUT_DATA_BY_ID_SUCCESS = "PUT_DATA_BY_ID_SUCCESS";
export const PUT_DATA_BY_ID_ERROR = "PUT_DATA_BY_ID_ERROR";
