/*
 *
 * ListTestimonial constants
 *
 */

export const FETCH_TESTIMONIAL_REQUEST = 'FETCH_TESTIMONIAL_REQUEST';
export const FETCH_TESTIMONIAL_SUCCESS = 'FETCH_TESTIMONIAL_SUCCESS'
export const FETCH_TESTIMONIAL_ERROR = 'FETCH_TESTIMONIAL_ERROR'

export const PATCH_TESTIMONIAL_REQUEST = "FETCH_TESTIMONIAL_REQUEST";
export const PATCH_TESTIMONIAL_SUCCESS = "PATCH_TESTIMONIAL_SUCCESS";
export const PATCH_TESTIMONIAL_ERROR = "PATCH_TESTIMONIAL_ERROR"

